<?php
/**
 * Created by PhpStorm.
 * User: OOM-Administrator
 * Date: 2018/4/23
 * Time: 14:51
 */

namespace oom\api\frontend\services;


use Yii;
use yii\web\IdentityInterface;
use oom\api\components\request\ApiService;
use oom\api\components\response\JSONResult;
use oom\api\models\forms\ApiAuthForm;

class AuthService extends ApiService
{

    public $apiMethod = [
        'market.ghs.auth.token.get' => 'apiGetToken',
        'market.ghs.auth.user.rule.get' => 'apiGetUserRule'
    ];


    /**
     * 定义接口名，指定回调方法
     * @var array $apiMethod
     */
    public function setApiMethod($items = [])
    {
        $this->apiMethod = array_merge($this->apiMethod, $items);
    }

    public function getApiMethod()
    {
        return parent::getApiMethod(); // TODO: Change the autogenerated stub
    }

    /**
     * @param $postData
     * @return string
     */
    public function apiGetToken($postData)
    {
        $jsonResult = new JSONResult();
        $model = new ApiAuthForm();
        $model->setAttributes(Yii::$app->request->post());
        if ($user = $model->login()) {
            if ($user instanceof IdentityInterface) {
                $jsonResult->data = ['access-token' => $user->api_token];
            } else {
                $jsonResult->setErrorCode('102');
                $jsonResult->setErrorMessage($user->errors);
            }
        } else {
            $jsonResult->setErrorCode('103');
            $jsonResult->setErrorMessage($model->errors);
        }
        return $jsonResult;
    }
}