<?php

namespace oom\api\admin\controllers;

use luya\admin\ngrest\base\Controller;

/**
 * Apiauth User Controller.
 * 
 * File has been created with `crud/create` command. 
 */
class ApiAuthUserController extends Controller
{
    /**
     * @var string The path to the model which is the provider for the rules and fields.
     */
    public $modelClass = 'oom\api\models\APIAuthUser';

    /**
     * @param bool $inline
     * @param bool $relation
     * @param bool $arrayIndex
     * @param bool $modelClass
     * @param bool $modelSelection
     * @return string
     * @throws \Exception
     */
    public function actionIndex(
        $inline = false,
        $relation = false,
        $arrayIndex = false,
        $modelClass = false,
        $modelSelection = false
    ){
        return parent::actionIndex($inline, $relation, $arrayIndex, $modelClass,
            $modelSelection); // TODO: Change the autogenerated stub
    }

}